version : "3.9"

services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    env_file: .env
    image: mariadb
    restart: unless-stopped
    networks:
      - inside
    volumes:
      - mariadb-volume:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-u", "$MARIADB_USER", "-p$MARIADB_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    depends_on:
      mariadb:
        condition: service_healthy
    env_file: .env
    image: wordpress
    restart: unless-stopped
    networks:
      - inside
    volumes:
      - wordpress-volume:/var/www/wordpress
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    depends_on:
      wordpress:
    restart: unless-stopped
    networks:
      -inside

networks:
  inside:

volumes:
  mariadb-volume:
    driver: local
    driver_opts:
      device: /home/aliens/data/database
      type: volume
      o: bind
  wordpress-volume:
    driver: local
    driver_opts:
      device: /home/aliens/data/wordpress
      type: volume
      o: bind
