version : "3.9"

services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    env_file: .env
    image: mariadb
    networks:
      - inception_network
    volumes:
      - mariadb-volume:/var/lib/mysql
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-u", "$MARIADB_USER", "-p $MARIADB_USER_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 10

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    depends_on:
      mariadb:
        condition: service_healthy
    env_file: .env
    image: wordpress
    networks:
      - inception_network
    volumes:
      - wordpress-volume:/var/www/html
    restart: unless-stopped

networks:
  inception_network:

volumes:
  mariadb-volume:
    driver: local
    driver_opts:
      device: /home/aliens/data/database
      type: volume
      o: bind
  wordpress-volume:
    driver: local
    driver_opts:
      device: /home/aliens/data/wordpress
      type: volume
      o: bind
