version : "3.9"

services:
  mariadb:
    container_name: mariadb
    build: ./mariadb
    env_file: .env
    image: mariadb
    networks:
      - inside
    volumes:
      - mariadb-volume:/var/lib/mysql
    ports:
      - 3306
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-u", "$MARIADB_USER", "-p $MARIADB_USER_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 10

  wordpress:
    container_name: wordpress
    build: ./wordpress
    env_file: .env
    image: wordpress
    networks:
      - inside
     # - outside
    volumes:
      - wordpress-volume:/var/www/wordpress
    depends_on:
      mariadb:
        condition: service_healthy
    restart: unless-stopped
      
  # nginx:
  #   container_name: nginx
  #   build: ./nginx
  #   image: nginx
  #   networks:
  #     - outside
  #   depends_on:
  #     - wordpress
  #   ports:
  #     - "443:443"
  #   volumes:
  #     - "wordpress-volume:/var/www/html"
  #   restart: unless-stopped

networks:
  inside:
  # outside:

volumes:
  mariadb-volume:
    driver: local
    driver_opts:
      device: /home/aliens/data/database
      type: volume
      o: bind
  wordpress-volume:
    driver: local
    driver_opts:
      device: /home/aliens/data/wordpress
      type: volume
      o: bind
