version : "3.9"

services:
  mariadb:
    container_name: mariadb
    build: ./mariadb
    env_file: .env
    image: mariadb
    restart: unless-stopped
    networks:
      - inception_network
    volumes:
      - mariadb-volume:/var/lib/mysql
    # healthcheck:
    #   test: ["CMD", "mysqladmin", "ping", "-u", "$MARIADB_USER", "-p $MARIADB_USER_PASSWORD"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 10

  # wordpress:
  #   container_name: wordpress
  #   build: ./wordpress
  #   image: wordpress
  #   networks:
  #     - inception_network
  #   depends_on:
  #     mariadb:
  #       condition: service_started
  #   env_file: .env
  #   volumes:
  #     - wordpress-volume:/var/www/html
  #   restart: unless-stopped
      
  # nginx:
  #   container_name: nginx
  #   build: ./nginx
  #   image: nginx
  #   networks:
  #     - inception_network
  #   depends_on:
  #     - wordpress
  #   ports:
  #     - "443:443"
  #   volumes:
  #     - "wordpress-volume:/var/www/html"
  #   restart: unless-stopped

networks:
  inception_network:

volumes:
  mariadb-volume:
    driver: local
    driver_opts:
      device: /home/aliens/data/database
      type: volume
      o: bind
  # wordpress-volume:
  #   driver: local
  #   driver_opts:
  #     device: /home/aliens/data/wordpress
  #     type: volume
  #     o: bind