/**Creation of database**/
CREATE DATABASE $MARIADB_DATABASE;
CREATE USER '&MARIADB_USER'@'%' IDENTIFIED BY 'MARIADB_USER_PASSWORD';
GRANT ALL PRIVILEGES ON $MARIADB_DATABASE.* TO $MARIADB_USER@'%';

FLUSH PRIVILEGES;