DROP USER 'root'@'localhost';
CREAYE USER 'root'@'localhost' IDENTIFIED BY '$MARIADB_ROOT_PASSWORD'
GRANT ALL PRIVILEGES ON *.* TO 'root'@'localhost' WITH GRANT OPTIONS;

CREATE DATABASE $MARIADB_DATABASE;
CREATE USER '$MARIADB_USER'@'%' IDENTIFIED by '$MARIADB_PASSWORD';
GRANT ALL PRIVILEGES ON $MARIADB_DATABASE.* TO '$MARIADB_USER'@'%';

FLUSH PRIVILEGES;
