# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Dockerfile                                         :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: aliens <aliens@student.s19.be>             +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/09/28 14:08:45 by aliens            #+#    #+#              #
#    Updated: 2022/10/06 15:04:20 by aliens           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

FROM debian:buster

RUN	apt-get update \
	&& apt-get upgrade -y \
	&& apt-get install -y curl php7.3 php7.3-fpm php7.3-mysql

RUN	curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar \
	&& chmod +x wp-cli.phar \
	&& mv wp-cli.phar /usr/local/bin/wp \
	&& mkdir -p /var/www/wordpress \
	&& chown -R www-data:www-data /var/www/wordpress

RUN wp core download --path="/var/www/wordpress/" --allow-root

COPY utils/entrypoint.sh ./

ENTRYPOINT [ "bash", "entrypoint.sh" ]



